name: Build and Deploy to S3
on:
  push:
    branches:
      - main # Trigger the workflow on push to the main branch
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grants write access to the repository contents, including submodules

    steps:
      - name: Checkout main repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: false # Disable automatic submodule handling

      - name: Update submodule URL to HTTPS
        run: |
          git submodule sync --recursive
          git submodule foreach 'git config --local url."https://github.com/".insteadOf "git@github.com:"'
          git submodule update --init --recursive

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Install Protobuf Compiler (protoc) Version 3.20.3
        run: |
          sudo apt-get update
          wget https://github.com/protocolbuffers/protobuf/releases/download/v3.20.3/protoc-3.20.3-linux-x86_64.zip
          unzip protoc-3.20.3-linux-x86_64.zip -d protoc3
          sudo mv protoc3/bin/* /usr/local/bin/
          sudo mv protoc3/include/* /usr/local/include/
          rm -rf protoc-3.20.3-linux-x86_64.zip protoc3

      - name: Make gRPC Client Script Executable
        run: chmod +x scripts/grpc-client.sh

      - name: Run gRPC Client Script
        run: bash scripts/grpc-client.sh

      - name: Build the project
        run: npm run build

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws s3 cp ./dist/app.min.js s3://${{ secrets.S3_BUCKET_NAME }}/public/scripts/app.min.js \
            --region $AWS_REGION --acl public-read

      - name: Invalidate CloudFront cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E3SJXANXL6IYCB \
            --paths "/public/scripts/*"
